zone: ""
sonosGateway: "http://localhost:5005"
deviceName: "Logitech USB Receiver"

debug: true
refreshConfig: 30

bindings:
  106:
    - path: 
      - "volume/+5"

  105: 
    - path:
        - "volume/-7"

